Global:
  use_gpu: True
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 500
  save_model_dir: ./output/competition_my_srn_balance_20210520_rgb
  save_epoch_step: 1
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 10000]
  cal_metric_during_train: True
  pretrained_model: /media/cv/05e0b7d2-56e9-4af1-8c14-037b49555090/xiaorui.feng/paddle/PaddleOCR/output/competition_my_srn_balance_20210519_rgb/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: /media/cv/05e0b7d2-56e9-4af1-8c14-037b49555090/xiaorui.feng/paddle/PaddleOCR/train_data/label_dict.txt
  character_type: ch
  max_text_length: 25
  num_heads: 8
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_srn_20210525.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    name: Cosine
    learning_rate: 0.001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform:
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512

Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/train_rgb/
    label_file_list: ["./train_data/train_rgb/train_20210517.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
          use_tia: True
          aug_prob: 0.4
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [1, 32, 320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: False
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/train_rgb/
    label_file_list: ["./train_data/train_rgb/LabelTest.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [1, 32, 320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] 
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 4
