Global:
  debug: false
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 1000
  save_model_dir: ./output/rec_chinese_lite_v2.0_0706
  save_epoch_step: 3
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: false
  pretrained_model: ./pretrain_models/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: /media/cv/05e0b7d2-56e9-4af1-8c14-037b49555090/xiaorui.feng/paddle/PaddleOCR/train_data/label_dict.txt
  character_type: ch
  max_text_length: 28
  infer_mode: false
  use_space_char: true
  save_res_path: ./output/rec/predicts_chinese_lite_v2.0.txt
  distributed: false
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 5.0e-05
  regularizer:
    name: L2
    factor: 1.0e-05
Architecture:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 1
    model_name: small
    small_stride:
    - 1
    - 2
    - 2
    - 2
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 64
  Head:
    name: CTCHead
    fc_decay: 4.0e-05
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /media/cv/05e0b7d2-56e9-4af1-8c14-037b49555090/xiaorui.feng/paddle/PaddleOCR/train_data/train_rgb/
    label_file_list:
    - /media/cv/05e0b7d2-56e9-4af1-8c14-037b49555090/xiaorui.feng/paddle/PaddleOCR/train_data/train_rgb/train_20210611(copy).txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 168
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /media/cv/05e0b7d2-56e9-4af1-8c14-037b49555090/xiaorui.feng/paddle/PaddleOCR/train_data/train_rgb/
    label_file_list:
    - /media/cv/05e0b7d2-56e9-4af1-8c14-037b49555090/xiaorui.feng/paddle/PaddleOCR/train_data/train_rgb/LabelTest_0.1.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 8
